package com.pp.carrers.app.model.services.common;

import java.util.Locale;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 04 17:02:57 IST 2016
// ---------------------------------------------------------------------
public interface ppCarrersService extends ApplicationModule {
    void carrersExec(String pid);

    String carrersCriteria(String cc_pid, String cc_pjobtitle,
                           String cc_pjobreq);

    String carrersSearch(String am_search);

    String executePPCarrersview(Locale lang);
}
