package com.tacme.pp.model.common.service.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 19 12:09:46 GST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PPAppModuleClient extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PPAppModuleClient() {
    }
}
