package com.pp.carrers.app.model.services.client;

import com.pp.carrers.app.model.services.common.ppCarrersService;

import java.util.Locale;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 04 17:02:57 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ppCarrersServiceClient extends ApplicationModuleImpl implements ppCarrersService {
    /**
     * This is the default constructor (do not remove).
     */
    public ppCarrersServiceClient() {
    }


    public void carrersExec(String pid) {
        Object _ret =
            this.riInvokeExportedMethod(this,"carrersExec",new String [] {"java.lang.String"},new Object[] {pid});
        return;
    }

    public String carrersCriteria(String cc_pid, String cc_pjobtitle,
                                  String cc_pjobreq) {
        Object _ret =
            this.riInvokeExportedMethod(this,"carrersCriteria",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {cc_pid, cc_pjobtitle, cc_pjobreq});
        return (String)_ret;
    }

    public String carrersSearch(String am_search) {
        Object _ret =
            this.riInvokeExportedMethod(this,"carrersSearch",new String [] {"java.lang.String"},new Object[] {am_search});
        return (String)_ret;
    }

    public String executePPCarrersview(Locale lang) {
        Object _ret =
            this.riInvokeExportedMethod(this,"executePPCarrersview",new String [] {"java.util.Locale"},new Object[] {lang});
        return (String)_ret;
    }
}
