package com.pp.tacme.proxies.PaymentServices;

import com.pp.tacme.proxies.PaymentServices.types.CancelPaymentSoapResponse;
import com.pp.tacme.proxies.PaymentServices.types.CompletePaymentSoapResponse;
import com.pp.tacme.proxies.PaymentServices.types.GetPaymentStatusSoapResponse;
import com.pp.tacme.proxies.PaymentServices.types.ObjectFactory;
import com.pp.tacme.proxies.PaymentServices.types.PaymentGetStatusResponse;
import com.pp.tacme.proxies.PaymentServices.types.PaymentServiceResponse;
import com.pp.tacme.proxies.PaymentServices.types.RefundPaymentSoapResponse;
import com.pp.tacme.proxies.PaymentServices.types.VoidPaymentSoapResponse;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

@WebService(wsdlLocation="http://172.25.1.202/PMRWeb/PaymentRouter/PaymentService.svc?wsdl",
  targetNamespace="http://tempuri.org/", name="IPaymentServiceSoap")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface IPaymentServiceSoap
{
  @WebMethod(operationName="GetPaymentStatusSoap", action="http://tempuri.org/IPaymentServiceSoap/GetPaymentStatusSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/GetPaymentStatusSoap",
    output="http://tempuri.org/IPaymentServiceSoap/GetPaymentStatusSoapResponse")
  @ResponseWrapper(localName="GetPaymentStatusSoapResponse",
    targetNamespace="http://tempuri.org/", className="com.pp.tacme.proxies.PaymentServices.types.GetPaymentStatusSoapResponse")
  @RequestWrapper(localName="GetPaymentStatusSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.GetPaymentStatusSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="GetPaymentStatusSoapResult")
  public PaymentGetStatusResponse getPaymentStatusSoap(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="GetPaymentStatusSoap", action="http://tempuri.org/IPaymentServiceSoap/GetPaymentStatusSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/GetPaymentStatusSoap",
    output="http://tempuri.org/IPaymentServiceSoap/GetPaymentStatusSoapResponse")
  @ResponseWrapper(localName="GetPaymentStatusSoapResponse",
    targetNamespace="http://tempuri.org/", className="com.pp.tacme.proxies.PaymentServices.types.GetPaymentStatusSoapResponse")
  @RequestWrapper(localName="GetPaymentStatusSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.GetPaymentStatusSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="GetPaymentStatusSoapResult")
  public Response<GetPaymentStatusSoapResponse> getPaymentStatusSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="GetPaymentStatusSoap", action="http://tempuri.org/IPaymentServiceSoap/GetPaymentStatusSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/GetPaymentStatusSoap",
    output="http://tempuri.org/IPaymentServiceSoap/GetPaymentStatusSoapResponse")
  @ResponseWrapper(localName="GetPaymentStatusSoapResponse",
    targetNamespace="http://tempuri.org/", className="com.pp.tacme.proxies.PaymentServices.types.GetPaymentStatusSoapResponse")
  @RequestWrapper(localName="GetPaymentStatusSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.GetPaymentStatusSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="GetPaymentStatusSoapResult")
  public Future<?> getPaymentStatusSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash,
    AsyncHandler<GetPaymentStatusSoapResponse> asyncHandler);

  @WebMethod(operationName="CompletePaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/CompletePaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/CompletePaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/CompletePaymentSoapResponse")
  @ResponseWrapper(localName="CompletePaymentSoapResponse",
    targetNamespace="http://tempuri.org/", className="com.pp.tacme.proxies.PaymentServices.types.CompletePaymentSoapResponse")
  @RequestWrapper(localName="CompletePaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.CompletePaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="CompletePaymentSoapResult")
  public PaymentServiceResponse completePaymentSoap(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="CompletePaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/CompletePaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/CompletePaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/CompletePaymentSoapResponse")
  @ResponseWrapper(localName="CompletePaymentSoapResponse",
    targetNamespace="http://tempuri.org/", className="com.pp.tacme.proxies.PaymentServices.types.CompletePaymentSoapResponse")
  @RequestWrapper(localName="CompletePaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.CompletePaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="CompletePaymentSoapResult")
  public Response<CompletePaymentSoapResponse> completePaymentSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="CompletePaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/CompletePaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/CompletePaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/CompletePaymentSoapResponse")
  @ResponseWrapper(localName="CompletePaymentSoapResponse",
    targetNamespace="http://tempuri.org/", className="com.pp.tacme.proxies.PaymentServices.types.CompletePaymentSoapResponse")
  @RequestWrapper(localName="CompletePaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.CompletePaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="CompletePaymentSoapResult")
  public Future<?> completePaymentSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash,
    AsyncHandler<CompletePaymentSoapResponse> asyncHandler);

  @WebMethod(operationName="CancelPaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/CancelPaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/CancelPaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/CancelPaymentSoapResponse")
  @ResponseWrapper(localName="CancelPaymentSoapResponse", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.CancelPaymentSoapResponse")
  @RequestWrapper(localName="CancelPaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.CancelPaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="CancelPaymentSoapResult")
  public PaymentServiceResponse cancelPaymentSoap(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="CancelPaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/CancelPaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/CancelPaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/CancelPaymentSoapResponse")
  @ResponseWrapper(localName="CancelPaymentSoapResponse", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.CancelPaymentSoapResponse")
  @RequestWrapper(localName="CancelPaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.CancelPaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="CancelPaymentSoapResult")
  public Response<CancelPaymentSoapResponse> cancelPaymentSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="CancelPaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/CancelPaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/CancelPaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/CancelPaymentSoapResponse")
  @ResponseWrapper(localName="CancelPaymentSoapResponse", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.CancelPaymentSoapResponse")
  @RequestWrapper(localName="CancelPaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.CancelPaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="CancelPaymentSoapResult")
  public Future<?> cancelPaymentSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash,
    AsyncHandler<CancelPaymentSoapResponse> asyncHandler);

  @WebMethod(operationName="RefundPaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/RefundPaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/RefundPaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/RefundPaymentSoapResponse")
  @ResponseWrapper(localName="RefundPaymentSoapResponse", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.RefundPaymentSoapResponse")
  @RequestWrapper(localName="RefundPaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.RefundPaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="RefundPaymentSoapResult")
  public PaymentServiceResponse refundPaymentSoap(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="RefundPaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/RefundPaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/RefundPaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/RefundPaymentSoapResponse")
  @ResponseWrapper(localName="RefundPaymentSoapResponse", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.RefundPaymentSoapResponse")
  @RequestWrapper(localName="RefundPaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.RefundPaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="RefundPaymentSoapResult")
  public Response<RefundPaymentSoapResponse> refundPaymentSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="RefundPaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/RefundPaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/RefundPaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/RefundPaymentSoapResponse")
  @ResponseWrapper(localName="RefundPaymentSoapResponse", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.RefundPaymentSoapResponse")
  @RequestWrapper(localName="RefundPaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.RefundPaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="RefundPaymentSoapResult")
  public Future<?> refundPaymentSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash,
    AsyncHandler<RefundPaymentSoapResponse> asyncHandler);

  @WebMethod(operationName="VoidPaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/VoidPaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/VoidPaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/VoidPaymentSoapResponse")
  @ResponseWrapper(localName="VoidPaymentSoapResponse", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.VoidPaymentSoapResponse")
  @RequestWrapper(localName="VoidPaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.VoidPaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="VoidPaymentSoapResult")
  public PaymentServiceResponse voidPaymentSoap(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="VoidPaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/VoidPaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/VoidPaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/VoidPaymentSoapResponse")
  @ResponseWrapper(localName="VoidPaymentSoapResponse", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.VoidPaymentSoapResponse")
  @RequestWrapper(localName="VoidPaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.VoidPaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="VoidPaymentSoapResult")
  public Response<VoidPaymentSoapResponse> voidPaymentSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash);

  @WebMethod(operationName="VoidPaymentSoap", action="http://tempuri.org/IPaymentServiceSoap/VoidPaymentSoap")
  @Action(input="http://tempuri.org/IPaymentServiceSoap/VoidPaymentSoap",
    output="http://tempuri.org/IPaymentServiceSoap/VoidPaymentSoapResponse")
  @ResponseWrapper(localName="VoidPaymentSoapResponse", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.VoidPaymentSoapResponse")
  @RequestWrapper(localName="VoidPaymentSoap", targetNamespace="http://tempuri.org/",
    className="com.pp.tacme.proxies.PaymentServices.types.VoidPaymentSoap")
  @WebResult(targetNamespace="http://tempuri.org/", name="VoidPaymentSoapResult")
  public Future<?> voidPaymentSoapAsync(@WebParam(targetNamespace="http://tempuri.org/",
      name="PurchaseId")
    String purchaseId, @WebParam(targetNamespace="http://tempuri.org/",
      name="SecureHash")
    String secureHash, AsyncHandler<VoidPaymentSoapResponse> asyncHandler);
}
