package com.pp.news.ae.model.services.client;

import com.pp.news.ae.model.services.common.PortalNewsService;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 19 12:09:16 GST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PortalNewsServiceClient extends ApplicationModuleImpl implements PortalNewsService {
    /**
     * This is the default constructor (do not remove).
     */
    public PortalNewsServiceClient() {
    }


    public String ret_view_newsquerry(int rkey) {
        Object _ret =
            this.riInvokeExportedMethod(this,"ret_view_newsquerry",new String [] {"int"},new Object[] {new Integer(rkey)});
        return (String)_ret;
    }

    public String ret_view_newsquerry_ar(int rkey) {
        Object _ret =
            this.riInvokeExportedMethod(this,"ret_view_newsquerry_ar",new String [] {"int"},new Object[] {new Integer(rkey)});
        return (String)_ret;
    }

    public void setImagePath(String path) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setImagePath",new String [] {"java.lang.String"},new Object[] {path});
        return;
    }
}
