package model.services;

import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 04 13:48:18 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SMSPrjServiceDefImpl extends ApplicationModuleDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SMSPrjServiceDefImpl() {
    }
}
