package model.services;

import java.sql.CallableStatement;

import java.sql.SQLException;

import model.services.common.SMSPrjService;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 04 13:48:18 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SMSPrjServiceImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SMSPrjServiceImpl() {
    }

    /**
     * Container's getter for SendsmsPortalView1.
     * @return SendsmsPortalView1
     */
    public ViewObjectImpl getSendsmsPortalView1() {
        return (ViewObjectImpl)findViewObject("SendsmsPortalView1");
    }
    public void executeSMSproc(String p_mobno, String p_subj) {
        System.out.println ("Moblenumber :: "+p_mobno);
            System.out.println ("Subject :: "+p_subj);
            try{
            DBTransactionImpl dbti = (DBTransactionImpl)getDBTransaction();
            CallableStatement statement =
                dbti.createCallableStatement(("BEGIN " + "SENDSMS_PORTAL(?,?);" +
                                              "END;"), 0);
            try {
                statement.setString(1, p_mobno);
                statement.setString(2, p_subj);                
                statement.execute();
            } catch (SQLException sqlerr) {
                throw new JboException(sqlerr);
            } finally {
                try {
                    if (statement != null) {
                        statement.close();
                    }
                } catch (SQLException closeerr) {
                    throw new JboException(closeerr);
                }
            }
            }catch (Exception e){
                e.printStackTrace();
            }
        }
}

