package com.pp.newsletter.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 22 10:53:32 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewsletterSubscriptionImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        NsId {
            public Object get(NewsletterSubscriptionImpl obj) {
                return obj.getNsId();
            }

            public void put(NewsletterSubscriptionImpl obj, Object value) {
                obj.setNsId((Number)value);
            }
        }
        ,
        NsName {
            public Object get(NewsletterSubscriptionImpl obj) {
                return obj.getNsName();
            }

            public void put(NewsletterSubscriptionImpl obj, Object value) {
                obj.setNsName((String)value);
            }
        }
        ,
        NsEmail {
            public Object get(NewsletterSubscriptionImpl obj) {
                return obj.getNsEmail();
            }

            public void put(NewsletterSubscriptionImpl obj, Object value) {
                obj.setNsEmail((String)value);
            }
        }
        ,
        NsCategories {
            public Object get(NewsletterSubscriptionImpl obj) {
                return obj.getNsCategories();
            }

            public void put(NewsletterSubscriptionImpl obj, Object value) {
                obj.setNsCategories((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(NewsletterSubscriptionImpl object);

        public abstract void put(NewsletterSubscriptionImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int NSID = AttributesEnum.NsId.index();
    public static final int NSNAME = AttributesEnum.NsName.index();
    public static final int NSEMAIL = AttributesEnum.NsEmail.index();
    public static final int NSCATEGORIES = AttributesEnum.NsCategories.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NewsletterSubscriptionImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.pp.newsletter.model.entities.NewsletterSubscription");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for NsId, using the alias name NsId.
     * @return the NsId
     */
    public Number getNsId() {
        return (Number)getAttributeInternal(NSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for NsId.
     * @param value value to set the NsId
     */
    public void setNsId(Number value) {
        setAttributeInternal(NSID, value);
    }

    /**
     * Gets the attribute value for NsName, using the alias name NsName.
     * @return the NsName
     */
    public String getNsName() {
        return (String)getAttributeInternal(NSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for NsName.
     * @param value value to set the NsName
     */
    public void setNsName(String value) {
        setAttributeInternal(NSNAME, value);
    }

    /**
     * Gets the attribute value for NsEmail, using the alias name NsEmail.
     * @return the NsEmail
     */
    public String getNsEmail() {
        return (String)getAttributeInternal(NSEMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for NsEmail.
     * @param value value to set the NsEmail
     */
    public void setNsEmail(String value) {
        setAttributeInternal(NSEMAIL, value);
    }

    /**
     * Gets the attribute value for NsCategories, using the alias name NsCategories.
     * @return the NsCategories
     */
    public String getNsCategories() {
        return (String)getAttributeInternal(NSCATEGORIES);
    }

    /**
     * Sets <code>value</code> as the attribute value for NsCategories.
     * @param value value to set the NsCategories
     */
    public void setNsCategories(String value) {
        setAttributeInternal(NSCATEGORIES, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param nsId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number nsId) {
        return new Key(new Object[]{nsId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("CATG_SEQ",getDBTransaction());
        this.setNsId(seq.getSequenceNumber());
    }
}
