package model.services.client;

import model.services.common.SMSPrjService;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 04 15:24:41 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SMSPrjServiceClient extends ApplicationModuleImpl implements SMSPrjService {
    /**
     * This is the default constructor (do not remove).
     */
    public SMSPrjServiceClient() {
    }

    public void executeSMSproc(String p_mobno, String p_subj) {
        Object _ret =
            this.riInvokeExportedMethod(this,"executeSMSproc",new String [] {"java.lang.String","java.lang.String"},new Object[] {p_mobno, p_subj});
        return;
    }
}
