package com.pp.carrers.app.model.services;

import com.pp.carrers.app.model.services.common.ppCarrersService;
import com.pp.carrers.app.model.views.PpCarrersViewImpl;

import java.util.Locale;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaManager;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 04 17:01:01 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ppCarrersServiceImpl extends ApplicationModuleImpl implements ppCarrersService {
    /**
     * This is the default constructor (do not remove).
     */
    public ppCarrersServiceImpl() {
    }

    /**
     * Container's getter for PpCarrersView1.
     * @return PpCarrersView1
     */
    public PpCarrersViewImpl getPpCarrersView1() {
        return (PpCarrersViewImpl)findViewObject("PpCarrersView1");
    }

    /**
     * Container's getter for StatusROVO1.
     * @return StatusROVO1
     */
    public ViewObjectImpl getStatusROVO1() {
        return (ViewObjectImpl)findViewObject("StatusROVO1");
    }

    /**
     * Container's getter for PpCarrersDefView1.
     * @return PpCarrersDefView1
     */
    public ViewObjectImpl getPpCarrersDefView1() {
        return (ViewObjectImpl)findViewObject("PpCarrersDefView1");
    }

    /**
     *  Set the row and execute
     */
    public void carrersExec(String pid) {
        if (pid != null) {
            ViewObject carrersPortalView = this.getPpCarrersDefView1();
            carrersPortalView.setNamedWhereClauseParam("pid", pid);
            carrersPortalView.executeQuery();
        }
    }

    /**
     * Container's getter for UcmConfigView1.
     * @return UcmConfigView1
     */
    public ViewObjectImpl getUcmConfigView1() {
        return (ViewObjectImpl)findViewObject("UcmConfigView1");
    }

    /**
     * execute the view criteria in carrers view
     */
    public String carrersCriteria(String cc_pid, String cc_pjobtitle,
                                  String cc_pjobreq) {
        String ret = "N";
        try {
            ViewObject carrersView = this.getPpCarrersView1();
            carrersView.setNamedWhereClauseParam("p_posid", cc_pid);
            carrersView.setNamedWhereClauseParam("p_jobtitle", cc_pjobtitle);
            carrersView.setNamedWhereClauseParam("p_jobreq", cc_pjobreq);
            ViewCriteriaManager vcm = carrersView.getViewCriteriaManager();
            ViewCriteria vc = vcm.getViewCriteria("PpCarrersViewCriteria");
            carrersView.applyViewCriteria(vc);
            carrersView.executeQuery();
            ret = "Y";
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ret;
    }
    
    /**
     * execute the view criteria in carrers view
     */
    public String carrersSearch(String am_search) {
        String ret = "N";
        try {
            ViewObject carrersView = this.getPpCarrersView1();
            carrersView.setNamedWhereClauseParam("p_search", am_search);            
//            ViewCriteriaManager vcm = carrersView.getViewCriteriaManager();
//            ViewCriteria vc = vcm.getViewCriteria("carrersSearchVC");
//            carrersView.applyViewCriteria(vc);
            carrersView.executeQuery();
            ret = "Y";
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ret;
    }
    
    /**
     *  Execute the carrer view
     */
    public String executePPCarrersview(Locale lang){
        String ret = "nogo";
        try{
        ViewObject carrersView = this.getPpCarrersView1();
        String langs = lang.toString();            
//            String langs = "en";
        carrersView.setNamedWhereClauseParam("p_lang", langs);
        carrersView.executeQuery();             
            ret = "go";
        }catch (Exception e){
            e.printStackTrace();
        }
        return ret;
    }


    /**
     * Container's getter for NationalityView1.
     * @return NationalityView1
     */
    public ViewObjectImpl getNationalityView1() {
        return (ViewObjectImpl)findViewObject("NationalityView1");
    }

    /**
     * Container's getter for VacanciesAdminView1.
     * @return VacanciesAdminView1
     */
    public ViewObjectImpl getVacanciesAdminView1() {
        return (ViewObjectImpl)findViewObject("VacanciesAdminView1");
    }

    /**
     * Container's getter for VacanciesAdminToPpCarrers1.
     * @return VacanciesAdminToPpCarrers1
     */
    public ViewLinkImpl getVacanciesAdminToPpCarrers1() {
        return (ViewLinkImpl)findViewLink("VacanciesAdminToPpCarrers1");
    }

    /**
     * Container's getter for VacanciesAdminView2.
     * @return VacanciesAdminView2
     */
    public ViewObjectImpl getVacanciesAdminView2() {
        return (ViewObjectImpl)findViewObject("VacanciesAdminView2");
    }
}
