package com.pp.evts.ae.model.services.client;

import com.pp.evts.ae.model.services.common.PortalEvtsAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 18 01:02:44 GST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PortalEvtsAMClient extends ApplicationModuleImpl implements PortalEvtsAM {
    /**
     * This is the default constructor (do not remove).
     */
    public PortalEvtsAMClient() {
    }

    public String ret_view_events(int rkey) {
        Object _ret =
            this.riInvokeExportedMethod(this,"ret_view_events",new String [] {"int"},new Object[] {new Integer(rkey)});
        return (String)_ret;
    }

    public String ret_view_events_ar(int rkey) {
        Object _ret =
            this.riInvokeExportedMethod(this,"ret_view_events_ar",new String [] {"int"},new Object[] {new Integer(rkey)});
        return (String)_ret;
    }
}
