package com.tacme.pp.model.common.ROVO.userprofile;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 19 12:13:10 GST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidateUserLoginRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getId();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        Email {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getEmail();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setEmail((String)value);
            }
        }
        ,
        Password {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getPassword();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setPassword((String)value);
            }
        }
        ,
        FirstName {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getFirstName();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setFirstName((String)value);
            }
        }
        ,
        LastName {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getLastName();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setLastName((String)value);
            }
        }
        ,
        FamilyName {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getFamilyName();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setFamilyName((String)value);
            }
        }
        ,
        Mobile {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getMobile();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setMobile((String)value);
            }
        }
        ,
        Dob {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getDob();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setDob((String)value);
            }
        }
        ,
        Education {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getEducation();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setEducation((String)value);
            }
        }
        ,
        Nationality {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getNationality();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setNationality((String)value);
            }
        }
        ,
        PasswordHint {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getPasswordHint();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setPasswordHint((String)value);
            }
        }
        ,
        Occupation {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getOccupation();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setOccupation((String)value);
            }
        }
        ,
        EmiratesId {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getEmiratesId();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setEmiratesId((String)value);
            }
        }
        ,
        EmiratesIdExpiry {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getEmiratesIdExpiry();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setEmiratesIdExpiry((String)value);
            }
        }
        ,
        UnionNo {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getUnionNo();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setUnionNo((String)value);
            }
        }
        ,
        Status {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getStatus();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        ApprovedDate {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getApprovedDate();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setApprovedDate((Date)value);
            }
        }
        ,
        CreatedDate {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        ModifiedDate {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setModifiedDate((Date)value);
            }
        }
        ,
        StatusReason {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getStatusReason();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setStatusReason((String)value);
            }
        }
        ,
        RegistrationLang {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getRegistrationLang();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setRegistrationLang((String)value);
            }
        }
        ,
        ModifiedByPerson {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getModifiedByPerson();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setModifiedByPerson((Number)value);
            }
        }
        ,
        ClientIp {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getClientIp();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setClientIp((String)value);
            }
        }
        ,
        UpdatedById {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getUpdatedById();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setUpdatedById((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        ResetPwd {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getResetPwd();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setResetPwd((Number)value);
            }
        }
        ,
        AppRef {
            public Object get(ValidateUserLoginRowImpl obj) {
                return obj.getAppRef();
            }

            public void put(ValidateUserLoginRowImpl obj, Object value) {
                obj.setAppRef((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ValidateUserLoginRowImpl object);

        public abstract void put(ValidateUserLoginRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int FAMILYNAME = AttributesEnum.FamilyName.index();
    public static final int MOBILE = AttributesEnum.Mobile.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int EDUCATION = AttributesEnum.Education.index();
    public static final int NATIONALITY = AttributesEnum.Nationality.index();
    public static final int PASSWORDHINT = AttributesEnum.PasswordHint.index();
    public static final int OCCUPATION = AttributesEnum.Occupation.index();
    public static final int EMIRATESID = AttributesEnum.EmiratesId.index();
    public static final int EMIRATESIDEXPIRY = AttributesEnum.EmiratesIdExpiry.index();
    public static final int UNIONNO = AttributesEnum.UnionNo.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int APPROVEDDATE = AttributesEnum.ApprovedDate.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int STATUSREASON = AttributesEnum.StatusReason.index();
    public static final int REGISTRATIONLANG = AttributesEnum.RegistrationLang.index();
    public static final int MODIFIEDBYPERSON = AttributesEnum.ModifiedByPerson.index();
    public static final int CLIENTIP = AttributesEnum.ClientIp.index();
    public static final int UPDATEDBYID = AttributesEnum.UpdatedById.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int RESETPWD = AttributesEnum.ResetPwd.index();
    public static final int APPREF = AttributesEnum.AppRef.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ValidateUserLoginRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Id.
     * @return the Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Id.
     * @param value value to set the  Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email.
     * @return the Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email.
     * @param value value to set the  Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Password.
     * @return the Password
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Password.
     * @param value value to set the  Password
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FirstName.
     * @return the FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FirstName.
     * @param value value to set the  FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastName.
     * @return the LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastName.
     * @param value value to set the  LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FamilyName.
     * @return the FamilyName
     */
    public String getFamilyName() {
        return (String) getAttributeInternal(FAMILYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FamilyName.
     * @param value value to set the  FamilyName
     */
    public void setFamilyName(String value) {
        setAttributeInternal(FAMILYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Mobile.
     * @return the Mobile
     */
    public String getMobile() {
        return (String) getAttributeInternal(MOBILE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Mobile.
     * @param value value to set the  Mobile
     */
    public void setMobile(String value) {
        setAttributeInternal(MOBILE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Dob.
     * @return the Dob
     */
    public String getDob() {
        return (String) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dob.
     * @param value value to set the  Dob
     */
    public void setDob(String value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Education.
     * @return the Education
     */
    public String getEducation() {
        return (String) getAttributeInternal(EDUCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Education.
     * @param value value to set the  Education
     */
    public void setEducation(String value) {
        setAttributeInternal(EDUCATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Nationality.
     * @return the Nationality
     */
    public String getNationality() {
        return (String) getAttributeInternal(NATIONALITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Nationality.
     * @param value value to set the  Nationality
     */
    public void setNationality(String value) {
        setAttributeInternal(NATIONALITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PasswordHint.
     * @return the PasswordHint
     */
    public String getPasswordHint() {
        return (String) getAttributeInternal(PASSWORDHINT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PasswordHint.
     * @param value value to set the  PasswordHint
     */
    public void setPasswordHint(String value) {
        setAttributeInternal(PASSWORDHINT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Occupation.
     * @return the Occupation
     */
    public String getOccupation() {
        return (String) getAttributeInternal(OCCUPATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Occupation.
     * @param value value to set the  Occupation
     */
    public void setOccupation(String value) {
        setAttributeInternal(OCCUPATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EmiratesId.
     * @return the EmiratesId
     */
    public String getEmiratesId() {
        return (String) getAttributeInternal(EMIRATESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmiratesId.
     * @param value value to set the  EmiratesId
     */
    public void setEmiratesId(String value) {
        setAttributeInternal(EMIRATESID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EmiratesIdExpiry.
     * @return the EmiratesIdExpiry
     */
    public String getEmiratesIdExpiry() {
        return (String) getAttributeInternal(EMIRATESIDEXPIRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmiratesIdExpiry.
     * @param value value to set the  EmiratesIdExpiry
     */
    public void setEmiratesIdExpiry(String value) {
        setAttributeInternal(EMIRATESIDEXPIRY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UnionNo.
     * @return the UnionNo
     */
    public String getUnionNo() {
        return (String) getAttributeInternal(UNIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnionNo.
     * @param value value to set the  UnionNo
     */
    public void setUnionNo(String value) {
        setAttributeInternal(UNIONNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ApprovedDate.
     * @return the ApprovedDate
     */
    public Date getApprovedDate() {
        return (Date) getAttributeInternal(APPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ApprovedDate.
     * @param value value to set the  ApprovedDate
     */
    public void setApprovedDate(Date value) {
        setAttributeInternal(APPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedDate.
     * @param value value to set the  CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ModifiedDate.
     * @return the ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ModifiedDate.
     * @param value value to set the  ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatusReason.
     * @return the StatusReason
     */
    public String getStatusReason() {
        return (String) getAttributeInternal(STATUSREASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatusReason.
     * @param value value to set the  StatusReason
     */
    public void setStatusReason(String value) {
        setAttributeInternal(STATUSREASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RegistrationLang.
     * @return the RegistrationLang
     */
    public String getRegistrationLang() {
        return (String) getAttributeInternal(REGISTRATIONLANG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RegistrationLang.
     * @param value value to set the  RegistrationLang
     */
    public void setRegistrationLang(String value) {
        setAttributeInternal(REGISTRATIONLANG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ModifiedByPerson.
     * @return the ModifiedByPerson
     */
    public Number getModifiedByPerson() {
        return (Number) getAttributeInternal(MODIFIEDBYPERSON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ModifiedByPerson.
     * @param value value to set the  ModifiedByPerson
     */
    public void setModifiedByPerson(Number value) {
        setAttributeInternal(MODIFIEDBYPERSON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ClientIp.
     * @return the ClientIp
     */
    public String getClientIp() {
        return (String) getAttributeInternal(CLIENTIP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ClientIp.
     * @param value value to set the  ClientIp
     */
    public void setClientIp(String value) {
        setAttributeInternal(CLIENTIP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UpdatedById.
     * @return the UpdatedById
     */
    public Number getUpdatedById() {
        return (Number) getAttributeInternal(UPDATEDBYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UpdatedById.
     * @param value value to set the  UpdatedById
     */
    public void setUpdatedById(Number value) {
        setAttributeInternal(UPDATEDBYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate.
     * @param value value to set the  CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy.
     * @param value value to set the  LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate.
     * @param value value to set the  LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResetPwd.
     * @return the ResetPwd
     */
    public Number getResetPwd() {
        return (Number) getAttributeInternal(RESETPWD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResetPwd.
     * @param value value to set the  ResetPwd
     */
    public void setResetPwd(Number value) {
        setAttributeInternal(RESETPWD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AppRef.
     * @return the AppRef
     */
    public String getAppRef() {
        return (String) getAttributeInternal(APPREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AppRef.
     * @param value value to set the  AppRef
     */
    public void setAppRef(String value) {
        setAttributeInternal(APPREF, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
