package com.pp.evts.ae.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 29 19:56:58 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EventDetViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EventDetViewImpl() {
    }
}
