package com.pp.evts.ae.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 12 09:56:29 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EventDetDefViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EventDetDefViewImpl() {
    }
}
