package com.pp.evts.ae.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 18 01:02:44 GST 2015
// ---------------------------------------------------------------------
public interface PortalEvtsAM extends ApplicationModule {
    String ret_view_events(int rkey);

    String ret_view_events_ar(int rkey);
}
