package com.app.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 07 15:52:56 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuPublicuserViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PuPublicuserViewImpl() {
    }
}
