package com.app.model.views;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 07 15:52:53 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuPublicuserViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getId();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        Email {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getEmail();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setEmail((String)value);
            }
        }
        ,
        Password {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getPassword();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setPassword((String)value);
            }
        }
        ,
        FirstName {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getFirstName();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setFirstName((String)value);
            }
        }
        ,
        LastName {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getLastName();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setLastName((String)value);
            }
        }
        ,
        FamilyName {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getFamilyName();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setFamilyName((String)value);
            }
        }
        ,
        Mobile {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getMobile();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setMobile((String)value);
            }
        }
        ,
        Dob {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getDob();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setDob((String)value);
            }
        }
        ,
        Education {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getEducation();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setEducation((String)value);
            }
        }
        ,
        Nationality {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getNationality();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setNationality((String)value);
            }
        }
        ,
        PasswordHint {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getPasswordHint();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setPasswordHint((String)value);
            }
        }
        ,
        Occupation {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getOccupation();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setOccupation((String)value);
            }
        }
        ,
        EmiratesId {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getEmiratesId();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setEmiratesId((String)value);
            }
        }
        ,
        EmiratesIdExpiry {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getEmiratesIdExpiry();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setEmiratesIdExpiry((String)value);
            }
        }
        ,
        UnionNo {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getUnionNo();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setUnionNo((String)value);
            }
        }
        ,
        Status {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        ApprovedDate {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getApprovedDate();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setApprovedDate((Date)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        ModifiedDate {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setModifiedDate((Date)value);
            }
        }
        ,
        StatusReason {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getStatusReason();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setStatusReason((String)value);
            }
        }
        ,
        RegistrationLang {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getRegistrationLang();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setRegistrationLang((String)value);
            }
        }
        ,
        ModifiedByPerson {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getModifiedByPerson();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setModifiedByPerson((Number)value);
            }
        }
        ,
        ClientIp {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getClientIp();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setClientIp((String)value);
            }
        }
        ,
        UpdatedById {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getUpdatedById();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setUpdatedById((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        ResetPwd {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getResetPwd();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setResetPwd((Number)value);
            }
        }
        ,
        RowID {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getRowID();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setRowID((oracle.jbo.domain.RowID)value);
            }
        }
        ,
        Language {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getLanguage();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setLanguage((String)value);
            }
        }
        ,
        LOV_Switcher_nationality {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getLOV_Switcher_nationality();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setLOV_Switcher_nationality((String)value);
            }
        }
        ,
        chgpwrd {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getchgpwrd();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setchgpwrd((String)value);
            }
        }
        ,
        disableDates {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getdisableDates();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setdisableDates((Date)value);
            }
        }
        ,
        CountryNationalityListVwView1 {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getCountryNationalityListVwView1();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CountryNationalityEngView1 {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getCountryNationalityEngView1();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CountryNationalityArabView1 {
            public Object get(PuPublicuserViewRowImpl obj) {
                return obj.getCountryNationalityArabView1();
            }

            public void put(PuPublicuserViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PuPublicuserViewRowImpl object);

        public abstract void put(PuPublicuserViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int FAMILYNAME = AttributesEnum.FamilyName.index();
    public static final int MOBILE = AttributesEnum.Mobile.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int EDUCATION = AttributesEnum.Education.index();
    public static final int NATIONALITY = AttributesEnum.Nationality.index();
    public static final int PASSWORDHINT = AttributesEnum.PasswordHint.index();
    public static final int OCCUPATION = AttributesEnum.Occupation.index();
    public static final int EMIRATESID = AttributesEnum.EmiratesId.index();
    public static final int EMIRATESIDEXPIRY = AttributesEnum.EmiratesIdExpiry.index();
    public static final int UNIONNO = AttributesEnum.UnionNo.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int APPROVEDDATE = AttributesEnum.ApprovedDate.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int STATUSREASON = AttributesEnum.StatusReason.index();
    public static final int REGISTRATIONLANG = AttributesEnum.RegistrationLang.index();
    public static final int MODIFIEDBYPERSON = AttributesEnum.ModifiedByPerson.index();
    public static final int CLIENTIP = AttributesEnum.ClientIp.index();
    public static final int UPDATEDBYID = AttributesEnum.UpdatedById.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int RESETPWD = AttributesEnum.ResetPwd.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int LANGUAGE = AttributesEnum.Language.index();
    public static final int LOV_SWITCHER_NATIONALITY = AttributesEnum.LOV_Switcher_nationality.index();
    public static final int CHGPWRD = AttributesEnum.chgpwrd.index();
    public static final int DISABLEDATES = AttributesEnum.disableDates.index();
    public static final int COUNTRYNATIONALITYLISTVWVIEW1 = AttributesEnum.CountryNationalityListVwView1.index();
    public static final int COUNTRYNATIONALITYENGVIEW1 = AttributesEnum.CountryNationalityEngView1.index();
    public static final int COUNTRYNATIONALITYARABVIEW1 = AttributesEnum.CountryNationalityArabView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PuPublicuserViewRowImpl() {
    }

    /**
     * Gets PuPublicuser entity object.
     * @return the PuPublicuser
     */
    public EntityImpl getPuPublicuser() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for PASSWORD using the alias name Password.
     * @return the PASSWORD
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for PASSWORD using the alias name Password.
     * @param value value to set the PASSWORD
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for FAMILY_NAME using the alias name FamilyName.
     * @return the FAMILY_NAME
     */
    public String getFamilyName() {
        return (String) getAttributeInternal(FAMILYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FAMILY_NAME using the alias name FamilyName.
     * @param value value to set the FAMILY_NAME
     */
    public void setFamilyName(String value) {
        setAttributeInternal(FAMILYNAME, value);
    }

    /**
     * Gets the attribute value for MOBILE using the alias name Mobile.
     * @return the MOBILE
     */
    public String getMobile() {
        return (String) getAttributeInternal(MOBILE);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE using the alias name Mobile.
     * @param value value to set the MOBILE
     */
    public void setMobile(String value) {
        setAttributeInternal(MOBILE, value);
    }

    /**
     * Gets the attribute value for DOB using the alias name Dob.
     * @return the DOB
     */
    public String getDob() {
        return (String) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as attribute value for DOB using the alias name Dob.
     * @param value value to set the DOB
     */
    public void setDob(String value) {
        String reformattedStr = null;        
        SimpleDateFormat fromUser = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
        SimpleDateFormat myFormat = new SimpleDateFormat("dd-MM-yyyy");
        try {
            reformattedStr = myFormat.format(fromUser.parse(value));
        } catch (ParseException e) {
            e.printStackTrace();
        }        
        setAttributeInternal(DOB, reformattedStr);
    }

    /**
     * Gets the attribute value for EDUCATION using the alias name Education.
     * @return the EDUCATION
     */
    public String getEducation() {
        return (String) getAttributeInternal(EDUCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for EDUCATION using the alias name Education.
     * @param value value to set the EDUCATION
     */
    public void setEducation(String value) {
        setAttributeInternal(EDUCATION, value);
    }

    /**
     * Gets the attribute value for NATIONALITY using the alias name Nationality.
     * @return the NATIONALITY
     */
    public String getNationality() {
        return (String) getAttributeInternal(NATIONALITY);
    }

    /**
     * Sets <code>value</code> as attribute value for NATIONALITY using the alias name Nationality.
     * @param value value to set the NATIONALITY
     */
    public void setNationality(String value) {
        setAttributeInternal(NATIONALITY, value);
    }

    /**
     * Gets the attribute value for PASSWORD_HINT using the alias name PasswordHint.
     * @return the PASSWORD_HINT
     */
    public String getPasswordHint() {
        return (String) getAttributeInternal(PASSWORDHINT);
    }

    /**
     * Sets <code>value</code> as attribute value for PASSWORD_HINT using the alias name PasswordHint.
     * @param value value to set the PASSWORD_HINT
     */
    public void setPasswordHint(String value) {
        setAttributeInternal(PASSWORDHINT, value);
    }

    /**
     * Gets the attribute value for OCCUPATION using the alias name Occupation.
     * @return the OCCUPATION
     */
    public String getOccupation() {
        return (String) getAttributeInternal(OCCUPATION);
    }

    /**
     * Sets <code>value</code> as attribute value for OCCUPATION using the alias name Occupation.
     * @param value value to set the OCCUPATION
     */
    public void setOccupation(String value) {
        setAttributeInternal(OCCUPATION, value);
    }

    /**
     * Gets the attribute value for EMIRATES_ID using the alias name EmiratesId.
     * @return the EMIRATES_ID
     */
    public String getEmiratesId() {
        return (String) getAttributeInternal(EMIRATESID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMIRATES_ID using the alias name EmiratesId.
     * @param value value to set the EMIRATES_ID
     */
    public void setEmiratesId(String value) {
        setAttributeInternal(EMIRATESID, value);
    }

    /**
     * Gets the attribute value for EMIRATES_ID_EXPIRY using the alias name EmiratesIdExpiry.
     * @return the EMIRATES_ID_EXPIRY
     */
    public String getEmiratesIdExpiry() {
        return (String) getAttributeInternal(EMIRATESIDEXPIRY);
    }

    /**
     * Sets <code>value</code> as attribute value for EMIRATES_ID_EXPIRY using the alias name EmiratesIdExpiry.
     * @param value value to set the EMIRATES_ID_EXPIRY
     */
    public void setEmiratesIdExpiry(String value) {
        setAttributeInternal(EMIRATESIDEXPIRY, value);
    }

    /**
     * Gets the attribute value for UNION_NO using the alias name UnionNo.
     * @return the UNION_NO
     */
    public String getUnionNo() {
        return (String) getAttributeInternal(UNIONNO);
    }

    /**
     * Sets <code>value</code> as attribute value for UNION_NO using the alias name UnionNo.
     * @param value value to set the UNION_NO
     */
    public void setUnionNo(String value) {
        setAttributeInternal(UNIONNO, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for APPROVED_DATE using the alias name ApprovedDate.
     * @return the APPROVED_DATE
     */
    public Date getApprovedDate() {
        return (Date)getAttributeInternal(APPROVEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVED_DATE using the alias name ApprovedDate.
     * @param value value to set the APPROVED_DATE
     */
    public void setApprovedDate(Date value) {
        setAttributeInternal(APPROVEDDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date)getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for STATUS_REASON using the alias name StatusReason.
     * @return the STATUS_REASON
     */
    public String getStatusReason() {
        return (String) getAttributeInternal(STATUSREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_REASON using the alias name StatusReason.
     * @param value value to set the STATUS_REASON
     */
    public void setStatusReason(String value) {
        setAttributeInternal(STATUSREASON, value);
    }

    /**
     * Gets the attribute value for REGISTRATION_LANG using the alias name RegistrationLang.
     * @return the REGISTRATION_LANG
     */
    public String getRegistrationLang() {
        return (String) getAttributeInternal(REGISTRATIONLANG);
    }

    /**
     * Sets <code>value</code> as attribute value for REGISTRATION_LANG using the alias name RegistrationLang.
     * @param value value to set the REGISTRATION_LANG
     */
    public void setRegistrationLang(String value) {
        setAttributeInternal(REGISTRATIONLANG, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY_PERSON using the alias name ModifiedByPerson.
     * @return the MODIFIED_BY_PERSON
     */
    public Number getModifiedByPerson() {
        return (Number)getAttributeInternal(MODIFIEDBYPERSON);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY_PERSON using the alias name ModifiedByPerson.
     * @param value value to set the MODIFIED_BY_PERSON
     */
    public void setModifiedByPerson(Number value) {
        setAttributeInternal(MODIFIEDBYPERSON, value);
    }

    /**
     * Gets the attribute value for CLIENT_IP using the alias name ClientIp.
     * @return the CLIENT_IP
     */
    public String getClientIp() {
        return (String) getAttributeInternal(CLIENTIP);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_IP using the alias name ClientIp.
     * @param value value to set the CLIENT_IP
     */
    public void setClientIp(String value) {
        setAttributeInternal(CLIENTIP, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY_ID using the alias name UpdatedById.
     * @return the UPDATED_BY_ID
     */
    public Number getUpdatedById() {
        return (Number)getAttributeInternal(UPDATEDBYID);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY_ID using the alias name UpdatedById.
     * @param value value to set the UPDATED_BY_ID
     */
    public void setUpdatedById(Number value) {
        setAttributeInternal(UPDATEDBYID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for RESET_PWD using the alias name ResetPwd.
     * @return the RESET_PWD
     */
    public Number getResetPwd() {
        return (Number)getAttributeInternal(RESETPWD);
    }

    /**
     * Sets <code>value</code> as attribute value for RESET_PWD using the alias name ResetPwd.
     * @param value value to set the RESET_PWD
     */
    public void setResetPwd(Number value) {
        setAttributeInternal(RESETPWD, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Language.
     * @return the Language
     */
    public String getLanguage() {
        return (String) getAttributeInternal(LANGUAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Language.
     * @param value value to set the  Language
     */
    public void setLanguage(String value) {
        setAttributeInternal(LANGUAGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LOV_Switcher_nationality.
     * @return the LOV_Switcher_nationality
     */
    public String getLOV_Switcher_nationality() {
        return (String) getAttributeInternal(LOV_SWITCHER_NATIONALITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LOV_Switcher_nationality.
     * @param value value to set the  LOV_Switcher_nationality
     */
    public void setLOV_Switcher_nationality(String value) {
        setAttributeInternal(LOV_SWITCHER_NATIONALITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute chgpwrd.
     * @return the chgpwrd
     */
    public String getchgpwrd() {
        return (String) getAttributeInternal(CHGPWRD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute chgpwrd.
     * @param value value to set the  chgpwrd
     */
    public void setchgpwrd(String value) {
        setAttributeInternal(CHGPWRD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute disableDates.
     * @return the disableDates
     */
    public Date getdisableDates() {
        return (Date) getAttributeInternal(DISABLEDATES);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute disableDates.
     * @param value value to set the  disableDates
     */
    public void setdisableDates(Date value) {
        setAttributeInternal(DISABLEDATES, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryNationalityListVwView1.
     */
    public RowSet getCountryNationalityListVwView1() {
        return (RowSet)getAttributeInternal(COUNTRYNATIONALITYLISTVWVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryNationalityEngView1.
     */
    public RowSet getCountryNationalityEngView1() {
        return (RowSet)getAttributeInternal(COUNTRYNATIONALITYENGVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryNationalityArabView1.
     */
    public RowSet getCountryNationalityArabView1() {
        return (RowSet)getAttributeInternal(COUNTRYNATIONALITYARABVIEW1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
