package com.pp.news.ae.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 19 12:09:16 GST 2015
// ---------------------------------------------------------------------
public interface PortalNewsService extends ApplicationModule {
    String ret_view_newsquerry(int rkey);

    String ret_view_newsquerry_ar(int rkey);

    void setImagePath(String path);
}
