package com.pp.news.ae.model.services;

import com.pp.news.ae.model.services.common.PortalNewsService;

import com.pp.news.ae.model.views.NewsDetailsArViewImpl;
import com.pp.news.ae.model.views.NewsDetailsDefArViewImpl;
import com.pp.news.ae.model.views.NewsDetailsDefViewImpl;
import com.pp.news.ae.model.views.NewsDetailsViewImpl;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

import oracle.stellent.ridc.IdcClient;
import oracle.stellent.ridc.IdcClientException;
import oracle.stellent.ridc.IdcClientManager;
import oracle.stellent.ridc.IdcContext;
import oracle.stellent.ridc.model.DataBinder;
import oracle.stellent.ridc.protocol.ServiceResponse;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 19 12:08:18 GST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PortalNewsServiceImpl extends ApplicationModuleImpl implements PortalNewsService {
    private String username;
    private String password;
    private String url;
    private IdcClient idcClient;
    private IdcContext userContext;
    private DataBinder binder;

    /**
     * This is the default constructor (do not remove).
     */
    public PortalNewsServiceImpl() {
    }

    /**
     * Container's getter for NewsDetailsArView1.
     * @return NewsDetailsArView1
     */
    public ViewObjectImpl getNewsDetailsArView1() {
        return (ViewObjectImpl)findViewObject("NewsDetailsArView1");
    }

    /**
     * Container's getter for NewsDetailsView1.
     * @return NewsDetailsView1
     */
    public ViewObjectImpl getNewsDetailsView1() {
        return (ViewObjectImpl)findViewObject("NewsDetailsView1");
    }
    
    public String ret_view_newsquerry(int rkey) {
               try {
                   ViewObject newsdefview = this.getNewsDetailsDefView1();            
                   String newwhere = "NEWS_ID = "+rkey;
                   newsdefview.setWhereClause(newwhere);
                   newsdefview.executeQuery();            
                   return "Y";
               }catch (Exception e){
                   e.printStackTrace();
               }
               return null;
           }
        
        public String ret_view_newsquerry_ar(int rkey) {
               try {
                   ViewObject newsdefview = this.getNewsDetailsDefArView1();            
                   String newwhere = "NEWS_ID = "+rkey;
                   newsdefview.setWhereClause(newwhere);
                   newsdefview.executeQuery();            
                   return "Y";
               }catch (Exception e){
                   e.printStackTrace();
               }
               return null;
           }
        
        public void setUCMPathAr(){
            ViewObject ucmconfigview = this.getUcmConfigView1();
            ViewObject newsdetailsarview = this.getNewsDetailsArView1();
            ucmconfigview.setNamedWhereClauseParam("uctype", "N");
            ucmconfigview.executeQuery();
            if (ucmconfigview.getEstimatedRowCount() != 0){
                Row ucmconfigrow = ucmconfigview.first();
                this.username = (String)ucmconfigrow.getAttribute("UcUsername");
                this.password = (String)ucmconfigrow.getAttribute("UcPassword");
                String link = (String)ucmconfigrow.getAttribute("UcUrl");
                String port = (String)ucmconfigrow.getAttribute("UcPortno");
                url = link+":"+port;
                intiateConnection();
            }
            
        }
        
    public void intiateConnection() {
        try {
//            this.username = "weblogic";
//            this.password = "weblogic1";
//            this.url = "idc://192.168.3.113:4444";
            IdcClientManager manager = new IdcClientManager();
            this.idcClient = manager.createClient(this.url);
            this.userContext = new IdcContext(this.username, this.password);
            System.out.println ("Get the usercontext :: "+userContext);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    public String getURLFromdID(String dID) {        
        this.binder = this.idcClient.createBinder();
        try {
            this.binder.putLocal("IdcService", "DOC_INFO");
            this.binder.putLocal("dID", dID);
            ServiceResponse response =
                idcClient.sendRequest(this.userContext, this.binder);
            DataBinder respBinder = response.getResponseAsBinder();
            if (respBinder != null)
                return respBinder.getLocal("DocUrl");
        } catch (IdcClientException ice) {
            ice.printStackTrace();
        }
        return null;
    }

    /**
     * Container's getter for NewsDetailsDefView1.
     * @return NewsDetailsDefView1
     */
    public ViewObjectImpl getNewsDetailsDefView1() {
        return (ViewObjectImpl)findViewObject("NewsDetailsDefView1");
    }

    /**
     * Container's getter for NewsDetailsDefArView1.
     * @return NewsDetailsDefArView1
     */
    public ViewObjectImpl getNewsDetailsDefArView1() {
        return (ViewObjectImpl)findViewObject("NewsDetailsDefArView1");
    }
    
    /**
     *  Upload the image in path 
     *  Created by - Prasad 
     *  Date - 20/10/2015
     */
    public void setImagePath(String path){
        ViewObject ndvo = this.getNewsDetailsView1();
        Row ndr = ndvo.getCurrentRow();
        ndr.setAttribute("NewsPath", path);
    }

    /**
     * Container's getter for UcmConfigView1.
     * @return UcmConfigView1
     */
    public ViewObjectImpl getUcmConfigView1() {
        return (ViewObjectImpl)findViewObject("UcmConfigView1");
    }
}
