package com.pp.component.model.snc.services.client;


import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 14 10:24:52 GST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SNVAppModuleClient extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SNVAppModuleClient() {
    }

    public boolean isDuplicate(int cid) {
        Object _ret =
            this.riInvokeExportedMethod(this,"isDuplicate",new String [] {"int"},new Object[] {new Integer(cid)});
        return ((Boolean)_ret).booleanValue();
    }
}
