package com.tacme.pp.model.common.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 19 11:20:13 GST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BaseVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BaseVOImpl() {
    }
}
