package com.app.model.services;

import java.io.Serializable;

import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 24 04:23:35 PDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PPAppServicesDefImpl extends ApplicationModuleDefImpl implements Serializable{
    @SuppressWarnings("compatibility:6286912297384639488")
    private static final long serialVersionUID = 1L;

    /**
     * This is the default constructor (do not remove).
     */
    public PPAppServicesDefImpl() {
    }
}
