package com.pp.carrers.app.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 04 15:28:42 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PpCarrersViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PpCarrersViewImpl() {
    }

    /**
     * Returns the variable value for p_posid.
     * @return variable value for p_posid
     */
    public String getp_posid() {
        return (String)ensureVariableManager().getVariableValue("p_posid");
    }

    /**
     * Sets <code>value</code> for variable p_posid.
     * @param value value to bind as p_posid
     */
    public void setp_posid(String value) {
        ensureVariableManager().setVariableValue("p_posid", value);
    }

    /**
     * Returns the variable value for p_jobtitle.
     * @return variable value for p_jobtitle
     */
    public String getp_jobtitle() {
        return (String)ensureVariableManager().getVariableValue("p_jobtitle");
    }

    /**
     * Sets <code>value</code> for variable p_jobtitle.
     * @param value value to bind as p_jobtitle
     */
    public void setp_jobtitle(String value) {
        ensureVariableManager().setVariableValue("p_jobtitle", value);
    }

    /**
     * Returns the variable value for p_jobreq.
     * @return variable value for p_jobreq
     */
    public String getp_jobreq() {
        return (String)ensureVariableManager().getVariableValue("p_jobreq");
    }

    /**
     * Sets <code>value</code> for variable p_jobreq.
     * @param value value to bind as p_jobreq
     */
    public void setp_jobreq(String value) {
        ensureVariableManager().setVariableValue("p_jobreq", value);
    }

    /**
     * Returns the variable value for p_search.
     * @return variable value for p_search
     */
    public String getp_search() {
        return (String)ensureVariableManager().getVariableValue("p_search");
    }

    /**
     * Sets <code>value</code> for variable p_search.
     * @param value value to bind as p_search
     */
    public void setp_search(String value) {
        ensureVariableManager().setVariableValue("p_search", value);
    }

    /**
     * Returns the bind variable value for p_lang.
     * @return bind variable value for p_lang
     */
    public String getp_lang() {
        return (String)getNamedWhereClauseParam("p_lang");
    }

    /**
     * Sets <code>value</code> for bind variable p_lang.
     * @param value value to bind as p_lang
     */
    public void setp_lang(String value) {
        setNamedWhereClauseParam("p_lang", value);
    }
}
