package com.pp.carrers.app.model.views;

import com.pp.carrers.app.model.entities.PpCarrersImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 04 15:28:42 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PpCarrersViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PositionId {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getPositionId();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setPositionId((String)value);
            }
        }
        ,
        Status {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        CreateDate {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setCreateDate((Date)value);
            }
        }
        ,
        CloseDate {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getCloseDate();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setCloseDate((Date)value);
            }
        }
        ,
        JobTitle {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getJobTitle();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setJobTitle((String)value);
            }
        }
        ,
        JobResp {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getJobResp();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setJobResp((String)value);
            }
        }
        ,
        JobReq {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getJobReq();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setJobReq((String)value);
            }
        }
        ,
        CarrersUcmId {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getCarrersUcmId();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setCarrersUcmId((String)value);
            }
        }
        ,
        Lang {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getLang();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setLang((String)value);
            }
        }
        ,
        Statusdecl {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getStatusdecl();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setStatusdecl((String)value);
            }
        }
        ,
        CloseCB {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getCloseCB();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setCloseCB((Boolean)value);
            }
        }
        ,
        VacanciesAdminView {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getVacanciesAdminView();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StatusROVO1 {
            public Object get(PpCarrersViewRowImpl obj) {
                return obj.getStatusROVO1();
            }

            public void put(PpCarrersViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PpCarrersViewRowImpl object);

        public abstract void put(PpCarrersViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int POSITIONID = AttributesEnum.PositionId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int CLOSEDATE = AttributesEnum.CloseDate.index();
    public static final int JOBTITLE = AttributesEnum.JobTitle.index();
    public static final int JOBRESP = AttributesEnum.JobResp.index();
    public static final int JOBREQ = AttributesEnum.JobReq.index();
    public static final int CARRERSUCMID = AttributesEnum.CarrersUcmId.index();
    public static final int LANG = AttributesEnum.Lang.index();
    public static final int STATUSDECL = AttributesEnum.Statusdecl.index();
    public static final int CLOSECB = AttributesEnum.CloseCB.index();
    public static final int VACANCIESADMINVIEW = AttributesEnum.VacanciesAdminView.index();
    public static final int STATUSROVO1 = AttributesEnum.StatusROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PpCarrersViewRowImpl() {
    }

    /**
     * Gets PpCarrers entity object.
     * @return the PpCarrers
     */
    public PpCarrersImpl getPpCarrers() {
        return (PpCarrersImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for POSITION_ID using the alias name PositionId.
     * @return the POSITION_ID
     */
    public String getPositionId() {
        return (String) getAttributeInternal(POSITIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for POSITION_ID using the alias name PositionId.
     * @param value value to set the POSITION_ID
     */
    public void setPositionId(String value) {
        setAttributeInternal(POSITIONID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for CLOSE_DATE using the alias name CloseDate.
     * @return the CLOSE_DATE
     */
    public Date getCloseDate() {
        return (Date) getAttributeInternal(CLOSEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLOSE_DATE using the alias name CloseDate.
     * @param value value to set the CLOSE_DATE
     */
    public void setCloseDate(Date value) {
        setAttributeInternal(CLOSEDATE, value);
    }

    /**
     * Gets the attribute value for JOB_TITLE using the alias name JobTitle.
     * @return the JOB_TITLE
     */
    public String getJobTitle() {
        return (String) getAttributeInternal(JOBTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_TITLE using the alias name JobTitle.
     * @param value value to set the JOB_TITLE
     */
    public void setJobTitle(String value) {
        setAttributeInternal(JOBTITLE, value);
    }

    /**
     * Gets the attribute value for JOB_RESP using the alias name JobResp.
     * @return the JOB_RESP
     */
    public String getJobResp() {
        return (String) getAttributeInternal(JOBRESP);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_RESP using the alias name JobResp.
     * @param value value to set the JOB_RESP
     */
    public void setJobResp(String value) {
        setAttributeInternal(JOBRESP, value);
    }

    /**
     * Gets the attribute value for JOB_REQ using the alias name JobReq.
     * @return the JOB_REQ
     */
    public String getJobReq() {
        return (String) getAttributeInternal(JOBREQ);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_REQ using the alias name JobReq.
     * @param value value to set the JOB_REQ
     */
    public void setJobReq(String value) {
        setAttributeInternal(JOBREQ, value);
    }

    /**
     * Gets the attribute value for CARRERS_UCM_ID using the alias name CarrersUcmId.
     * @return the CARRERS_UCM_ID
     */
    public String getCarrersUcmId() {
        return (String) getAttributeInternal(CARRERSUCMID);
    }

    /**
     * Sets <code>value</code> as attribute value for CARRERS_UCM_ID using the alias name CarrersUcmId.
     * @param value value to set the CARRERS_UCM_ID
     */
    public void setCarrersUcmId(String value) {
        setAttributeInternal(CARRERSUCMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Statusdecl.
     * @return the Statusdecl
     */
    public String getStatusdecl() {
        return (String) getAttributeInternal(STATUSDECL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Statusdecl.
     * @param value value to set the  Statusdecl
     */
    public void setStatusdecl(String value) {
        setAttributeInternal(STATUSDECL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CloseCB.
     * @return the CloseCB
     */
    public Boolean getCloseCB() {
        return (Boolean) getAttributeInternal(CLOSECB);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CloseCB.
     * @param value value to set the  CloseCB
     */
    public void setCloseCB(Boolean value) {
        setAttributeInternal(CLOSECB, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VacanciesAdminView.
     */
    public RowIterator getVacanciesAdminView() {
        return (RowIterator)getAttributeInternal(VACANCIESADMINVIEW);
    }

    /**
     * Gets the attribute value for LANG using the alias name Lang.
     * @return the LANG
     */
    public String getLang() {
        return (String) getAttributeInternal(LANG);
    }

    /**
     * Sets <code>value</code> as attribute value for LANG using the alias name Lang.
     * @param value value to set the LANG
     */
    public void setLang(String value) {
        setAttributeInternal(LANG, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StatusROVO1.
     */
    public RowSet getStatusROVO1() {
        return (RowSet)getAttributeInternal(STATUSROVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
