package com.pp.news.ae.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 29 18:00:49 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewsDetailsDefViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NewsDetailsDefViewImpl() {
    }
}
