package com.pp.evts.ae.model.services;

import com.pp.evts.ae.model.services.common.PortalEvtsAM;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 18 01:01:03 GST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PortalEvtsAMImpl extends ApplicationModuleImpl implements PortalEvtsAM {
    /**
     * This is the default constructor (do not remove).
     */
    public PortalEvtsAMImpl() {
    }

    /**
     * Container's getter for EventDetArView1.
     * @return EventDetArView1
     */
    public ViewObjectImpl getEventDetArView1() {
        return (ViewObjectImpl)findViewObject("EventDetArView1");
    }

    /**
     * Container's getter for EventDetLineArView1.
     * @return EventDetLineArView1
     */
    public ViewObjectImpl getEventDetLineArView1() {
        return (ViewObjectImpl)findViewObject("EventDetLineArView1");
    }

    /**
     * Container's getter for EventDetLineView1.
     * @return EventDetLineView1
     */
    public ViewObjectImpl getEventDetLineView1() {
        return (ViewObjectImpl)findViewObject("EventDetLineView1");
    }

    /**
     * Container's getter for EventDetView1.
     * @return EventDetView1
     */
    public ViewObjectImpl getEventDetView1() {
        return (ViewObjectImpl)findViewObject("EventDetView1");
    }

    /**
     * Container's getter for EventDetLineArView2.
     * @return EventDetLineArView2
     */
    public ViewObjectImpl getEventDetLineArView2() {
        return (ViewObjectImpl)findViewObject("EventDetLineArView2");
    }

    /**
     * Container's getter for EventDetLineView2.
     * @return EventDetLineView2
     */
    public ViewObjectImpl getEventDetLineView2() {
        return (ViewObjectImpl)findViewObject("EventDetLineView2");
    }

    /**
     * Container's getter for EventsLineArToDet1.
     * @return EventsLineArToDet1
     */
    public ViewLinkImpl getEventsLineArToDet1() {
        return (ViewLinkImpl)findViewLink("EventsLineArToDet1");
    }

    /**
     * Container's getter for EventsLineToDet1.
     * @return EventsLineToDet1
     */
    public ViewLinkImpl getEventsLineToDet1() {
        return (ViewLinkImpl)findViewLink("EventsLineToDet1");
    }
    
    public String ret_view_events (int rkey){
        try{
            ViewObject eventdefview = this.getEventDetDefView1();
            String eventwhere = "EVENT_ID ="+rkey;
            eventdefview.setWhereClause(eventwhere);
            eventdefview.executeQuery();            
            return "Y";
        }
        catch (Exception e){
            e.printStackTrace();
        }
        return null;
    }
    
    public String ret_view_events_ar (int rkey){
        try{
            ViewObject eventdefview = this.getEventDetDefArView1();
            String eventwhere = "EVENT_ID ="+rkey;
            eventdefview.setWhereClause(eventwhere);
            eventdefview.executeQuery();            
            return "Y";
        }
        catch (Exception e){
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Container's getter for EventDetDefView1.
     * @return EventDetDefView1
     */
    public ViewObjectImpl getEventDetDefView1() {
        return (ViewObjectImpl)findViewObject("EventDetDefView1");
    }

    /**
     * Container's getter for EventDetLineView3.
     * @return EventDetLineView3
     */
    public ViewObjectImpl getEventDetLineView3() {
        return (ViewObjectImpl)findViewObject("EventDetLineView3");
    }

    /**
     * Container's getter for EventsLineToDetDef1.
     * @return EventsLineToDetDef1
     */
    public ViewLinkImpl getEventsLineToDetDef1() {
        return (ViewLinkImpl)findViewLink("EventsLineToDetDef1");
    }

    /**
     * Container's getter for EventDetDefArView1.
     * @return EventDetDefArView1
     */
    public ViewObjectImpl getEventDetDefArView1() {
        return (ViewObjectImpl)findViewObject("EventDetDefArView1");
    }

    /**
     * Container's getter for EventDetLineArView3.
     * @return EventDetLineArView3
     */
    public ViewObjectImpl getEventDetLineArView3() {
        return (ViewObjectImpl)findViewObject("EventDetLineArView3");
    }

    /**
     * Container's getter for EventsLineARToDetDef1.
     * @return EventsLineARToDetDef1
     */
    public ViewLinkImpl getEventsLineARToDetDef1() {
        return (ViewLinkImpl)findViewLink("EventsLineARToDetDef1");
    }
}
