package com.tacme.pp.model.common.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 19 12:09:45 GST 2016
// ---------------------------------------------------------------------
public interface PPAppModule extends ApplicationModule {
}
