package com.pp.component.model.snc.services;



import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 14 10:18:40 GST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SNVAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SNVAppModuleImpl() {
    }

    /**
     * Container's getter for ComplainsSuggestionsView1.
     * @return ComplainsSuggestionsView1
     */
    public ViewObjectImpl getComplainsSuggestionsView1() {
        return (ViewObjectImpl)findViewObject("ComplainsSuggestionsView1");
    }

    /**
     * Container's getter for type1.
     * @return type1
     */
    public ViewObjectImpl gettype1() {
        return (ViewObjectImpl)findViewObject("type1");
    }

    /**
     * Container's getter for typeVO1.
     * @return typeVO1
     */
    public ViewObjectImpl gettypeVO1() {
        return (ViewObjectImpl)findViewObject("typeVO1");
    }

    public boolean isDuplicate(int cid) {
      if(cid==0)cid=1;
        String query =
            "SELECT * FROM COMPLAINS_SUGGESTIONS WHERE id = ?";
        PreparedStatement stmnt =
            getDBTransaction().createPreparedStatement(query, 1);

        try {  
            stmnt.setInt(1, cid);
        ResultSet result = null;
            result = stmnt.executeQuery();
            if (result.next()) {
System.out.println(">>"+result.getInt(1));
                    return true;
            }}
            catch (Exception e) {
                e.printStackTrace();
            }


            return false;
     
    }
}
